#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#

module "compute" {
  source = "./module-compute"

  aws_region            = var.aws_region
  cy_component          = var.cy_component
  cy_env                = var.cy_env
  cy_org                = var.cy_org
  cy_project            = var.cy_project
  database_enabled      = false
  database_env_var_name = ""
  database_resource     = ""
  res_selector          = "create"
  vm_disk_size          = 20
  vm_instance_type      = "t3a.small"
  vm_ports_in = [
    22,
    80,
    443,
    3000,
    8080
  ]
  vpc_id_inventory = ""
  vpc_id_manual    = ""
}

