#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#

module "compute" {
  source = "./module-compute"

  aws_region       = var.aws_region
  cy_component     = var.cy_component
  cy_env           = var.cy_env
  cy_org           = var.cy_org
  cy_project       = var.cy_project
  install_k3s      = var.install_k3s
  res_selector     = "create"
  vm_disk_size     = 20
  vm_instance_type = "t3a.small"
  vm_ports_in = [
    80,
    443,
    22
  ]
  vpc_id_aws       = ""
  vpc_id_inventory = ""
  vpc_id_manual    = ""
}

