#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#

module "compute" {
  source = "./module-compute"

  aws_region       = var.aws_region
  cycom            = var.cycom
  cyenv            = var.cyenv
  cyorg            = var.cyorg
  cypro            = var.cypro
  vm_disk_size     = 20
  vm_instance_type = "t3a.medium"
}

