#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#

module "s3" {
  source = "./module-s3"

  aws_region             = "eu-west-1"
  bucket_name            = "flatcar-os-ignition"
  custom_lifecycle_rules = false
  cy_component           = var.cy_component
  cy_env                 = var.cy_env
  cy_org                 = var.cy_org
  cy_project             = var.cy_project
  lifecycle_rules = [

  ]
  versioning_enabled = true
}

